### ISSUE TITLE
Add comparisons with teacher models

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-evaluation#16]
So we can see how much we are losing with the student models.

**Comment by andrenatal** [comment]
@eu9ene Do you know where the consortium host the teacher models of the ones we are shipping?

**Comment by marco-c** [comment]
Note metrics might be biased with student models, giving them better scores than they should have, so it will be interesting to see these results.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842782.
