### ISSUE TITLE
Add COMET metric support

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-evaluation#6]
https://github.com/Unbabel/COMET

Based on paper https://arxiv.org/abs/2107.10821

WMT21 metrics task results: https://aclanthology.org/2021.wmt-1.73.pdf

**Comment by andrenatal** [comment]
- [ ] Integrate comet's evaluation instrumentation
- [ ] Adapt reporting
- [ ] Incorporate needed changes to Dockerfile to run nvidia image plus instructions on readme
- [ ] Adapt circle job: https://github.com/mozilla/firefox-translations-models/blob/main/.circleci/config.yml
- [ ] Configure circle job to run on nvidia image
- [ ] Adapt evaluation scripts:
  - [ ] https://github.com/mozilla/firefox-translations-models/blob/main/scripts/eval.sh
  - [ ]  https://github.com/mozilla/firefox-translations-models/blob/main/scripts/update-results.sh
